---
resources:
  - name: pre-commit-git
    type: git
    source:
      branch: test-detection-concourse
      private_key: ((deploy-keys))
      uri: git@github.com:alphagov/gds-pre-commit.git

blocks:
  - config: &pre_commit_docker
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: gdscyber/cyber-security-concourse-base-image}
      inputs:
        - name: pre-commit-git

jobs:
  - name: pre_commit_tests
    serial: false
    plan:
      - get: pre-commit-git
        trigger: true

      - task: test_detection_keys
        config:
          <<: *pre_commit_docker
          run:
            path: bash
            args:
              - -exc
              - |
                mkdir /root/.ssh
                echo "Host github.com" >> /root/.ssh/config
                echo "  StrictHostKeyChecking no" >> /root/.ssh/config
                cat /root/.ssh/config

      - task: run_pre_commit_tests
        config:
          <<: *pre_commit_docker
          run:
            path: bash
            args:
              - -c
              - |
                python3 -m venv virtualenv
                source virtualenv/bin/activate
                cd pre-commit-git/test-detection
                pip install wheel
                pip install -r requirements-pipeline.txt
                pre-commit install -c .gds/.pre-commit-config.yaml
                git config --global core.hookspath ../global_install/hooks
                source ../concourse/bin/sts-assume-role.sh \
                'arn:aws:iam::103495720024:role/gds_pre_commit_tests_role' \
                'eu-west-2'
                make run
